name       : python-xmlschema
version    : 1.9.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/x/xmlschema/xmlschema-1.9.2.tar.gz : 3ce6fe408a8c0a0ca5917cbe6181a933dfb5cfade9714eeb07b6335f9aff7b10
license    : MIT
component  : programming.python
summary    : An XML Schema validator and decoder
description: |
    This library arises from the needs of a solid Python layer for processing XML Schema based files for MaX (Materials design at the Exascale) European project. A significant problem is the encoding and the decoding of the XML data files produced by different simulation software. Another important requirement is the XML data validation, in order to put the produced data under control. The lack of a suitable alternative for Python in the schema-based decoding of XML data has led to build this library. Obviously this library can be useful for other cases related to XML Schema based processing, not only for the original scope.
rundeps    :
    - python-elementpath
build      : |
    %python3_setup
install    : |
    %python3_install
