name       : python-xmlschema
version    : 2.1.1
release    : 5
source     :
    - https://github.com/sissaschool/xmlschema/archive/refs/tags/v2.1.1.tar.gz : eff61c0732eaf8ff089bfe37f7d941700e806257b2e26d3dc2a411e69a7b57b1
homepage   : https://github.com/sissaschool/xmlschema
license    : MIT
component  : programming.python
summary    : An XML Schema validator and decoder
description: |
    This library arises from the needs of a solid Python layer for processing XML Schema based files for MaX (Materials design at the Exascale) European project. A significant problem is the encoding and the decoding of the XML data files produced by different simulation software. Another important requirement is the XML data validation, in order to put the produced data under control. The lack of a suitable alternative for Python in the schema-based decoding of XML data has led to build this library. Obviously this library can be useful for other cases related to XML Schema based processing, not only for the original scope.
rundeps    :
    - python-elementpath
build      : |
    %python3_setup
install    : |
    %python3_install
