name       : python-xmlschema
version    : 1.11.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/x/xmlschema/xmlschema-1.11.0.tar.gz : 319f5e3e77beb6ab3b4166f699d9dafd59141487bd1a07675fd01af6483211a4
homepage   : https://github.com/sissaschool/xmlschema
license    : MIT
component  : programming.python
summary    : An XML Schema validator and decoder
description: |
    This library arises from the needs of a solid Python layer for processing XML Schema based files for MaX (Materials design at the Exascale) European project. A significant problem is the encoding and the decoding of the XML data files produced by different simulation software. Another important requirement is the XML data validation, in order to put the produced data under control. The lack of a suitable alternative for Python in the schema-based decoding of XML data has led to build this library. Obviously this library can be useful for other cases related to XML Schema based processing, not only for the original scope.
rundeps    :
    - python-elementpath
build      : |
    %python3_setup
install    : |
    %python3_install
